name: Create Joomla! Plugin install arcive


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    name: ZIP
    steps:
      - uses: actions/checkout@v1

      - name: Upload plugin artifact
        uses: actions/upload-artifact@master
        with:
          name: plg_system_seo_checklist
          path: src/
